from __future__ import annotations

import argparse
import itertools
from pathlib import Path
from typing import Any

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from wesad_modality_common import (
    DEFAULT_SEED,
    MODALITY_METRICS_DIR,
    MODALITY_MODEL_ROOT,
    align_probability,
    class_distribution,
    compute_binary_metrics,
    compute_oof_modality_probabilities,
    load_model_artifact,
    load_split,
    predict_with_artifact,
    print_metrics,
    save_json,
    save_model_artifact,
    select_threshold,
)

BVP_PROB_DIR = MODALITY_MODEL_ROOT / "bvp_probabilities"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train a leak-free late-fusion classifier and weighted probability fusion for WESAD."
    )
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument("--artifact-path", type=Path, default=MODALITY_MODEL_ROOT / "fusion_model.joblib")
    parser.add_argument("--metrics-path", type=Path, default=MODALITY_METRICS_DIR / "fusion_metrics.json")
    parser.add_argument("--ablation-path", type=Path, default=MODALITY_METRICS_DIR / "ablation_results.json")
    parser.add_argument("--config-path", type=Path, default=MODALITY_MODEL_ROOT.parent / "fusion_config.json")
    return parser.parse_args()


def load_cached_bvp_probabilities() -> dict[str, tuple[np.ndarray, np.ndarray]]:
    """Load pre-computed BVP probabilities from .npy cache (generated by compute_bvp_probabilities.py)."""
    results: dict[str, tuple[np.ndarray, np.ndarray]] = {}
    for split in ("train", "val", "test"):
        prob_path = BVP_PROB_DIR / f"{split}_probabilities.npy"
        label_path = BVP_PROB_DIR / f"{split}_labels.npy"
        if not prob_path.exists() or not label_path.exists():
            raise FileNotFoundError(
                f"BVP probability cache not found for {split}. "
                f"Run: python src/compute_bvp_probabilities.py first."
            )
        probs = np.load(prob_path).astype(np.float32)
        labels = np.load(label_path).astype(np.int64)
        results[split] = (probs, labels)
    return results


def select_fast_threshold(y_true: np.ndarray, probabilities: np.ndarray) -> tuple[float, dict[str, Any]]:
    thresholds = np.round(np.arange(0.10, 0.91, 0.01), 2)
    y_true_bool = (y_true == 1)
    preds = (probabilities[:, None] >= thresholds[None, :])  # shape (N, 81)

    tp = (preds & y_true_bool[:, None]).sum(axis=0)
    fp = (preds & (~y_true_bool[:, None])).sum(axis=0)
    fn = ((~preds) & y_true_bool[:, None]).sum(axis=0)

    denom = 2 * tp + fp + fn
    f1_scores = np.where(denom > 0, (2 * tp) / denom, 0.0)
    best_idx = int(np.argmax(f1_scores))
    best_thresh = float(thresholds[best_idx])
    best_metrics = compute_binary_metrics(y_true, probabilities, threshold=best_thresh)
    return best_thresh, best_metrics


def grid_search_weighted_fusion(
    val_probs_dict: dict[str, np.ndarray],
    y_val: np.ndarray,
    modality_subset: list[str],
    threshold_modality_map: dict[str, float],
    use_alignment: bool = True,
    weight_step: float = 0.05,
) -> tuple[dict[str, float], float, dict[str, Any]]:
    aligned_val: dict[str, np.ndarray] = {}
    for mod in modality_subset:
        if use_alignment:
            aligned_val[mod] = np.asarray(align_probability(val_probs_dict[mod], threshold_modality_map[mod]))
        else:
            aligned_val[mod] = val_probs_dict[mod]

    n_mods = len(modality_subset)
    if n_mods == 1:
        mod = modality_subset[0]
        best_threshold, best_metrics = select_fast_threshold(y_val, aligned_val[mod])
        return {mod: 1.0}, best_threshold, best_metrics

    steps = round(1.0 / weight_step)
    grid_points = [i * weight_step for i in range(steps + 1)]

    best_weights: dict[str, float] | None = None
    best_threshold: float | None = None
    best_metrics: dict[str, Any] | None = None

    for raw_weights in itertools.product(grid_points, repeat=n_mods):
        s = sum(raw_weights)
        if abs(s - 1.0) > 1e-5:
            continue
        weights_dict = {mod: w for mod, w in zip(modality_subset, raw_weights)}

        fused_prob = np.zeros(len(y_val), dtype=np.float32)
        for mod in modality_subset:
            fused_prob += weights_dict[mod] * aligned_val[mod]

        threshold, metrics = select_fast_threshold(y_val, fused_prob)

        is_better = False
        if best_metrics is None:
            is_better = True
        elif metrics["f1"] > best_metrics["f1"] + 1e-12:
            is_better = True
        elif abs(metrics["f1"] - best_metrics["f1"]) <= 1e-12:
            bvp_weight_new = weights_dict.get("bvp", 0.0)
            bvp_weight_curr = best_weights.get("bvp", 0.0) if best_weights else 0.0
            if bvp_weight_new > bvp_weight_curr + 1e-5:
                is_better = True

        if is_better:
            best_weights = weights_dict
            best_threshold = threshold
            best_metrics = metrics

    if best_weights is None or best_threshold is None or best_metrics is None:
        raise RuntimeError("Weighted grid search failed")

    return best_weights, best_threshold, best_metrics


def predict_weighted_fusion(
    probs_dict: dict[str, np.ndarray],
    weights: dict[str, float],
    threshold_modality_map: dict[str, float],
    use_alignment: bool = True,
) -> np.ndarray:
    fused_prob = np.zeros(len(next(iter(probs_dict.values()))), dtype=np.float32)
    for mod, w in weights.items():
        if w <= 0.0:
            continue
        if use_alignment:
            p_mod = align_probability(probs_dict[mod], threshold_modality_map[mod])
        else:
            p_mod = probs_dict[mod]
        fused_prob += w * p_mod
    return fused_prob


def main() -> None:
    args = parse_args()
    artifact_path = args.artifact_path.resolve()
    metrics_path = args.metrics_path.resolve()
    ablation_path = args.ablation_path.resolve()
    config_path = args.config_path.resolve()

    print("=" * 70)
    print("VITALAGENT - SCIENTIFIC MULTIMODAL FUSION & ABLATION STUDY")
    print("=" * 70)

    # 1. Load cached BVP Probabilities (generated by compute_bvp_probabilities.py)
    print("\n[1/5] Loading cached BVP probabilities...")
    bvp_probabilities = load_cached_bvp_probabilities()
    bvp_train_probs, y_train = bvp_probabilities["train"]
    bvp_val_probs, y_val = bvp_probabilities["val"]
    bvp_test_probs, y_test = bvp_probabilities["test"]

    # BVP threshold optimized on validation
    bvp_threshold, bvp_val_metrics = select_threshold(y_val, bvp_val_probs)
    bvp_test_metrics = compute_binary_metrics(y_test, bvp_test_probs, threshold=bvp_threshold)
    print(f"BVP Validation Threshold: {bvp_threshold:.4f} | Validation F1: {bvp_val_metrics['f1']:.4f}")
    print(f"BVP Test F1: {bvp_test_metrics['f1']:.4f} | ROC-AUC: {bvp_test_metrics['roc_auc']:.4f}")

    # 2. Compute OOF Predictions for EDA, TEMP, ACC on Train Split (Leak-Free Meta Training)
    print("\n[2/5] Computing subject-aware Out-of-Fold (OOF) predictions for EDA, TEMP, ACC...")
    eda_oof_probs = compute_oof_modality_probabilities("eda", seed=args.seed)
    temp_oof_probs = compute_oof_modality_probabilities("temp", seed=args.seed)
    acc_oof_probs = compute_oof_modality_probabilities("acc", seed=args.seed)

    # 3. Load Full Modality Models & Compute Val / Test Probabilities
    print("\n[3/5] Loading modality artifacts & predicting on Validation and Test...")
    eda_artifact = load_model_artifact(MODALITY_MODEL_ROOT / "eda_model.joblib")
    temp_artifact = load_model_artifact(MODALITY_MODEL_ROOT / "temp_model.joblib")
    acc_artifact = load_model_artifact(MODALITY_MODEL_ROOT / "acc_model.joblib")

    threshold_map = {
        "bvp": bvp_threshold,
        "eda": eda_artifact["threshold"],
        "temp": temp_artifact["threshold"],
        "acc": acc_artifact["threshold"],
    }

    X_train_eda, y_train_eda, _ = load_split("eda", "train")
    X_val_eda, y_val_eda, _ = load_split("eda", "val")
    X_test_eda, y_test_eda, _ = load_split("eda", "test")
    if not np.array_equal(y_train_eda, y_train):
        raise ValueError("Training labels for BVP and EDA do not align")

    eda_val_probs = predict_with_artifact(eda_artifact, X_val_eda)
    eda_test_probs = predict_with_artifact(eda_artifact, X_test_eda)

    X_train_temp, y_train_temp, _ = load_split("temp", "train")
    X_val_temp, y_val_temp, _ = load_split("temp", "val")
    X_test_temp, y_test_temp, _ = load_split("temp", "test")
    if not np.array_equal(y_train_temp, y_train):
        raise ValueError("Training labels for BVP and TEMP do not align")

    temp_val_probs = predict_with_artifact(temp_artifact, X_val_temp)
    temp_test_probs = predict_with_artifact(temp_artifact, X_test_temp)

    X_train_acc, y_train_acc, _ = load_split("acc", "train")
    X_val_acc, y_val_acc, _ = load_split("acc", "val")
    X_test_acc, y_test_acc, _ = load_split("acc", "test")
    if not np.array_equal(y_train_acc, y_train):
        raise ValueError("Training labels for BVP and ACC do not align")

    acc_val_probs = predict_with_artifact(acc_artifact, X_val_acc)
    acc_test_probs = predict_with_artifact(acc_artifact, X_test_acc)

    val_probs_dict = {
        "bvp": bvp_val_probs,
        "eda": eda_val_probs,
        "temp": temp_val_probs,
        "acc": acc_val_probs,
    }
    test_probs_dict = {
        "bvp": bvp_test_probs,
        "eda": eda_test_probs,
        "temp": temp_test_probs,
        "acc": acc_test_probs,
    }

    # 4. Train OOF Stacker Classifier
    print("\n[4/5] Training Logistic Regression Stacker on OOF training features...")
    X_train_oof = np.column_stack([bvp_train_probs, eda_oof_probs, temp_oof_probs, acc_oof_probs])
    stacker_model = Pipeline([
        ("scaler", StandardScaler()),
        ("classifier", LogisticRegression(max_iter=2000, class_weight="balanced", random_state=args.seed)),
    ])
    stacker_model.fit(X_train_oof, y_train)

    X_val_fusion = np.column_stack([bvp_val_probs, eda_val_probs, temp_val_probs, acc_val_probs])
    stacker_val_probs = stacker_model.predict_proba(X_val_fusion)[:, 1]
    stacker_threshold, stacker_val_metrics = select_threshold(y_val, stacker_val_probs)

    # 5. Ablation Study across Modality Combinations on VALIDATION
    print("\n" + "=" * 70)
    print("PHASE 4 — VALIDATION ABLATION & SYSTEM SELECTION")
    print("=" * 70)

    ablation_subsets = [
        ["bvp"],
        ["bvp", "eda"],
        ["bvp", "temp"],
        ["bvp", "acc"],
        ["bvp", "eda", "acc"],
        ["bvp", "eda", "temp", "acc"],
    ]

    ablation_results: dict[str, Any] = {}
    best_candidate_name = None
    best_candidate_val_f1 = -1.0
    best_candidate_config: dict[str, Any] | None = None

    # Evaluate Weighted Fusion (with and without threshold alignment) for each subset
    for subset in ablation_subsets:
        subset_name = " + ".join([m.upper() for m in subset])

        for use_align in (True, False):
            align_tag = "Aligned" if use_align else "Raw"
            cand_id = f"{subset_name} ({align_tag} Weighted)"
            weights, threshold, val_m = grid_search_weighted_fusion(
                val_probs_dict, y_val, subset, threshold_map, use_alignment=use_align
            )

            ablation_results[cand_id] = {
                "subset": subset,
                "type": "weighted_fusion",
                "use_alignment": use_align,
                "weights": weights,
                "threshold": threshold,
                "validation_metrics": val_m,
            }

            val_f1 = val_m["f1"]
            print(f"{cand_id:<35} | Val F1: {val_f1:.4f} | Acc: {val_m['accuracy']:.4f} | Rec: {val_m['recall']:.4f} | Threshold: {threshold:.2f}")

            if val_f1 > best_candidate_val_f1 + 1e-12:
                best_candidate_val_f1 = val_f1
                best_candidate_name = cand_id
                best_candidate_config = ablation_results[cand_id]

    # Also evaluate OOF Stacker
    stacker_id = "BVP + EDA + TEMP + ACC (OOF LR Stacker)"
    ablation_results[stacker_id] = {
        "subset": ["bvp", "eda", "temp", "acc"],
        "type": "stacker",
        "threshold": stacker_threshold,
        "validation_metrics": stacker_val_metrics,
    }
    print(f"{stacker_id:<35} | Val F1: {stacker_val_metrics['f1']:.4f} | Acc: {stacker_val_metrics['accuracy']:.4f} | Rec: {stacker_val_metrics['recall']:.4f} | Threshold: {stacker_threshold:.2f}")

    if stacker_val_metrics["f1"] > best_candidate_val_f1 + 1e-12:
        best_candidate_val_f1 = stacker_val_metrics["f1"]
        best_candidate_name = stacker_id
        best_candidate_config = ablation_results[stacker_id]

    print("\n" + "=" * 70)
    print(f"WINNING FUSION CONFIGURATION (SELECTED ON VALIDATION F1):")
    print(f"Strategy: {best_candidate_name}")
    print(f"Validation F1: {best_candidate_val_f1:.4f}")
    print("=" * 70)

    # 6. Freeze Selected Configuration and Evaluate ONCE on TEST Set
    print("\n" + "=" * 70)
    print("PHASE 6 — FINAL TEST EVALUATION (FROZEN CONFIGURATION)")
    print("=" * 70)

    for cand_id, config in ablation_results.items():
        if config["type"] == "weighted_fusion":
            fused_test_prob = predict_weighted_fusion(
                test_probs_dict,
                config["weights"],
                threshold_map,
                use_alignment=config["use_alignment"],
            )
            test_m = compute_binary_metrics(y_test, fused_test_prob, threshold=config["threshold"])
        else:
            X_test_fusion = np.column_stack([bvp_test_probs, eda_test_probs, temp_test_probs, acc_test_probs])
            stacker_test_probs = stacker_model.predict_proba(X_test_fusion)[:, 1]
            test_m = compute_binary_metrics(y_test, stacker_test_probs, threshold=config["threshold"])

        config["test_metrics"] = test_m

    assert best_candidate_config is not None, "No winning configuration was selected"
    winning_config: dict[str, Any] = best_candidate_config
    final_test_metrics: dict[str, Any] = winning_config["test_metrics"]

    print("\nFinal Selected System Test Performance:")
    print_metrics("Final Multimodal System (TEST)", final_test_metrics)

    print("\nComparing with Baseline BVP (TEST):")
    print_metrics("BVP Baseline (TEST)", bvp_test_metrics)

    improved = bool(final_test_metrics["f1"] > bvp_test_metrics["f1"])
    print(f"\nFinal Metric Comparison (TEST F1):")
    print(f"BVP Baseline F1   : {bvp_test_metrics['f1']:.4f}")
    print(f"Multimodal Fusion F1: {final_test_metrics['f1']:.4f}")
    print(f"Improved over BVP?: {'YES (+{:.4f})'.format(final_test_metrics['f1'] - bvp_test_metrics['f1']) if improved else 'NO'}")

    # If fusion did not improve over BVP, evaluate BVP as explicit fallback option
    final_active_weights = winning_config.get("weights", {"bvp": 1.0, "eda": 0.0, "temp": 0.0, "acc": 0.0})
    final_used_modalities = [mod for mod, w in final_active_weights.items() if w > 0.0] if "weights" in winning_config else winning_config["subset"]

    # 7. Save Artifacts
    fusion_artifact_payload = {
        "modality": "fusion",
        "selected_strategy": best_candidate_name,
        "type": winning_config["type"],
        "use_alignment": winning_config.get("use_alignment", True),
        "modality_thresholds": threshold_map,
        "weights": final_active_weights,
        "threshold": winning_config["threshold"],
        "validation_metrics": winning_config["validation_metrics"],
        "test_metrics": final_test_metrics,
        "bvp_test_metrics": bvp_test_metrics,
        "stacker_model": stacker_model if winning_config["type"] == "stacker" else None,
        "feature_names": ["bvp_probability", "eda_probability", "temp_probability", "acc_probability"],
        "train_class_distribution": class_distribution(y_train),
        "val_class_distribution": class_distribution(y_val),
        "test_class_distribution": class_distribution(y_test),
        "improved_over_bvp": improved,
    }
    save_model_artifact(artifact_path, fusion_artifact_payload)

    fusion_config_json = {
        "selected_strategy": best_candidate_name,
        "type": winning_config["type"],
        "use_alignment": winning_config.get("use_alignment", True),
        "modality_thresholds": threshold_map,
        "modality_weights": final_active_weights,
        "threshold": winning_config["threshold"],
        "used_modalities": final_used_modalities,
        "improved_over_bvp": improved,
        "validation_f1": winning_config["validation_metrics"]["f1"],
        "test_f1": final_test_metrics["f1"],
        "bvp_baseline_test_f1": bvp_test_metrics["f1"],
    }
    save_json(config_path, fusion_config_json)

    metrics_payload = {
        "modality": "fusion",
        "artifact_path": str(artifact_path),
        "config_path": str(config_path),
        "selected_strategy": best_candidate_name,
        "threshold": winning_config["threshold"],
        "validation_metrics": winning_config["validation_metrics"],
        "test_metrics": final_test_metrics,
        "bvp_baseline_test": bvp_test_metrics,
        "improved_over_bvp": improved,
        "class_distribution": {
            "train": class_distribution(y_train),
            "val": class_distribution(y_val),
            "test": class_distribution(y_test),
        },
    }
    save_json(metrics_path, metrics_payload)
    save_json(ablation_path, ablation_results)

    print(f"\nSaved fusion artifact: {artifact_path}")
    print(f"Saved fusion config  : {config_path}")
    print(f"Saved fusion metrics : {metrics_path}")
    print(f"Saved ablation JSON  : {ablation_path}")


if __name__ == "__main__":
    main()
