import { useState, useEffect } from "react";
import { FileText, FileBarChart2, AlertTriangle, Users, Download } from "lucide-react";
import Header from "../components/Header";
import { fetchReports, generateReport } from "../api/client";
import { ReportRow } from "../types";

const REPORT_TYPES = [
  {
    typeKey: "Individual",
    icon: <FileText size={20} />,
    title: "Individual Report",
    description: "Generate detailed report for a single patient, including SpO2 history.",
  },
  {
    typeKey: "Summary",
    icon: <FileBarChart2 size={20} />,
    title: "Summary Report",
    description: "Get summary of screenings for a date range.",
  },
  {
    typeKey: "Alerts",
    icon: <AlertTriangle size={20} />,
    title: "Alerts Report",
    description: "Download report of all alerts.",
  },
  {
    typeKey: "Community",
    icon: <Users size={20} />,
    title: "Community Report",
    description: "Overview of community health insights.",
  },
];

export default function Reports() {
  const [reportsList, setReportsList] = useState<ReportRow[]>([]);

  useEffect(() => {
    fetchReports().then(setReportsList);
  }, []);

  const handleGenerate = async (typeKey: string) => {
    const newRep = await generateReport(typeKey);
    setReportsList((prev) => [newRep, ...prev]);
  };

  return (
    <>
      <Header title="Reports" subtitle="Generate and download screening reports." />

      <div className="flex-1 overflow-y-auto p-6 space-y-5">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {REPORT_TYPES.map((r) => (
            <div key={r.title} className="bg-white rounded-card border border-border p-4">
              <div className="text-accent mb-2">{r.icon}</div>
              <div className="text-sm font-medium mb-1">{r.title}</div>
              <div className="text-xs text-ink-muted mb-3">{r.description}</div>
              <button
                onClick={() => handleGenerate(r.typeKey)}
                className="text-xs text-accent hover:underline font-medium"
              >
                Generate →
              </button>
            </div>
          ))}
        </div>

        <div>
          <div className="text-sm font-medium mb-2">Recent Reports</div>
          <div className="bg-white rounded-card border border-border overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-wash text-ink-muted text-left text-xs">
                  <th className="font-normal px-4 py-3">Report Name</th>
                  <th className="font-normal px-4 py-3">Type</th>
                  <th className="font-normal px-4 py-3">Generated On</th>
                  <th className="font-normal px-4 py-3">Generated By</th>
                  <th className="font-normal px-4 py-3">Action</th>
                </tr>
              </thead>
              <tbody>
                {reportsList.map((r, i) => (
                  <tr key={`${r.name}-${i}`} className="border-t border-border">
                    <td className="px-4 py-3 font-medium">{r.name}</td>
                    <td className="px-4 py-3">{r.type}</td>
                    <td className="px-4 py-3">{r.generatedOn}</td>
                    <td className="px-4 py-3">{r.generatedBy}</td>
                    <td className="px-4 py-3">
                      <button
                        onClick={() => alert(`Downloading ${r.name}...`)}
                        className="text-ink-muted hover:text-accent"
                      >
                        <Download size={16} />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </>
  );
}
